#!/bin/bash

node "./task-scripts/manager-package-version.js"

commit_denied=false

if git diff --cached --name-only | grep -q "^JavaScript/"; then
    git reset JavaScript
    echo -e "\033[31mCommit denied: changes in the 'JavaScript' directory cannot be committed.\033[0m"
    commit_denied=true
fi

if git diff --cached --name-only | grep -q "^SQL/"; then
    git reset SQL
    echo -e "\033[31mCommit denied: changes in the 'SQL' directory cannot be committed.\033[0m"
    commit_denied=true
fi

if [ "$commit_denied" = true ]; then
    exit 1
fi

ruby ./task-scripts/update_README_.rb
git add README.md